"""
make_sample_data.py
-------------------
Creates synthetic MARTINI-format .itp files for testing the data pipeline
when the real MARTINI download hasn't completed yet.

Generates 60 molecules:
  - 20 lipid-like   (5-8 beads, 4-7 bonds, 3-6 angles)
  - 20 polymer-like (6-12 beads, chain topology)
  - 20 small-mol    (3-5 beads, simple topology)

Spring constants are sampled from realistic MARTINI 3 distributions:
  k_bond  ~ Uniform(2000, 6000) kJ/mol/nm²
  r0      ~ Uniform(0.35, 0.55) nm
  k_angle ~ Uniform(15,   100)  kJ/mol/rad²
  theta0  ~ Uniform(90,   150)  degrees

Run:
    python make_sample_data.py
    python make_sample_data.py --n_mols 120 --out data/raw/martini3
"""

import os
import sys

# Ensure project root (cg_spring_gnn) is on sys.path and is current working directory
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)
os.chdir(PROJECT_ROOT)
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

import os
import random
import argparse
import numpy as np

random.seed(42)
np.random.seed(42)

# MARTINI 3 bead types representative set
BEAD_TYPES = {
    "apolar":       ["C1","C2","C3","C4","SC1","SC2","SC3","TC1","TC2"],
    "intermediate": ["N1","N2","N3","N4","SN1","SN2","TN1","TN2"],
    "polar":        ["P1","P2","P3","P4","P5","SP1","SP2","TP1","TP2"],
    "charged":      ["Q1","Q2","Qa","Qd"],
}
ALL_BEADS = [b for bs in BEAD_TYPES.values() for b in bs]

MASS_MAP  = {b: (36 if b.startswith("T") else 54 if b.startswith("S") else 72)
             for b in ALL_BEADS}
CHARGE_MAP= {"Qa": -1.0, "Qd": +1.0, "Q1": -0.5, "Q2": +0.5}


def rand_k_bond():
    return round(np.random.uniform(2000, 6000), 1)

def rand_r0():
    return round(np.random.uniform(0.35, 0.55), 4)

def rand_k_angle():
    return round(np.random.uniform(15, 120), 1)

def rand_theta0():
    return round(np.random.uniform(90, 150), 1)


def write_itp(path: str, mol_name: str, beads: list, bonds: list, angles: list):
    """Write a GROMACS-format ITP file."""
    with open(path, "w") as f:
        f.write(f"; Synthetic MARTINI 3 molecule: {mol_name}\n")
        f.write(f"; Generated by make_sample_data.py for pipeline testing\n\n")

        f.write("[ moleculetype ]\n")
        f.write(f"; name  nrexcl\n")
        f.write(f"{mol_name}  1\n\n")

        f.write("[ atoms ]\n")
        f.write("; nr  type  resnr residue atom cgnr charge mass\n")
        for i, (btype, bname) in enumerate(beads, start=1):
            charge = CHARGE_MAP.get(btype, 0.0)
            mass   = MASS_MAP.get(btype, 72.0)
            f.write(f"  {i}  {btype}  1  MOL  {bname}  {i}  {charge:.1f}  {mass:.1f}\n")

        f.write("\n[ bonds ]\n")
        f.write("; i  j  funct  r0[nm]  k[kJ/mol/nm2]\n")
        for (i, j, r0, k) in bonds:
            f.write(f"  {i}  {j}  1  {r0:.4f}  {k:.1f}\n")

        if angles:
            f.write("\n[ angles ]\n")
            f.write("; i  j  k  funct  theta0[deg]  k[kJ/mol/rad2]\n")
            for (i, j, k_, theta0, ka) in angles:
                f.write(f"  {i}  {j}  {k_}  2  {theta0:.1f}  {ka:.1f}\n")

        f.write("\n")


def make_lipid(mol_id: int) -> tuple:
    """Linear lipid-like molecule: head + tail beads."""
    n_head  = random.randint(1, 3)
    n_tail  = random.randint(3, 6)
    n_beads = n_head + n_tail
    mol_name = f"LIP{mol_id:03d}"

    head_types = [random.choice(BEAD_TYPES["polar"] + BEAD_TYPES["charged"])
                  for _ in range(n_head)]
    tail_types = [random.choice(BEAD_TYPES["apolar"]) for _ in range(n_tail)]
    all_types  = head_types + tail_types
    beads = [(t, f"B{i+1}") for i, t in enumerate(all_types)]

    bonds = [(i, i+1, rand_r0(), rand_k_bond()) for i in range(1, n_beads)]
    angles = [(i, i+1, i+2, rand_theta0(), rand_k_angle()) for i in range(1, n_beads-1)]

    return mol_name, beads, bonds, angles


def make_polymer(mol_id: int) -> tuple:
    """Linear polymer chain: all apolar or mixed beads."""
    n = random.randint(5, 12)
    mol_name = f"POL{mol_id:03d}"

    pool = BEAD_TYPES["apolar"] + BEAD_TYPES["intermediate"]
    beads = [(random.choice(pool), f"M{i+1}") for i in range(n)]
    bonds = [(i, i+1, rand_r0(), rand_k_bond()) for i in range(1, n)]
    angles = [(i, i+1, i+2, rand_theta0(), rand_k_angle()) for i in range(1, n-1)]

    return mol_name, beads, bonds, angles


def make_small_mol(mol_id: int) -> tuple:
    """Small molecule: 3-5 beads, ring or branched topology."""
    n = random.randint(3, 5)
    mol_name = f"SM{mol_id:03d}"

    pool = BEAD_TYPES["apolar"] + BEAD_TYPES["polar"] + BEAD_TYPES["intermediate"]
    beads = [(random.choice(pool), f"A{i+1}") for i in range(n)]

    # Linear bonds
    bonds = [(i, i+1, rand_r0(), rand_k_bond()) for i in range(1, n)]
    angles = [(i, i+1, i+2, rand_theta0(), rand_k_angle()) for i in range(1, n-1)]

    # Sometimes add a branch bond
    if n >= 4 and random.random() > 0.5:
        bonds.append((1, n, rand_r0(), rand_k_bond()))

    return mol_name, beads, bonds, angles


def main(n_per_class: int, out_dir: str):
    os.makedirs(out_dir, exist_ok=True)
    total = 0

    for i in range(n_per_class):
        for make_fn, prefix in [(make_lipid, "lip"),
                                  (make_polymer, "pol"),
                                  (make_small_mol, "sm")]:
            mol_name, beads, bonds, angles = make_fn(i)
            fname = os.path.join(out_dir, f"{prefix}_{mol_name}.itp")
            write_itp(fname, mol_name, beads, bonds, angles)
            total += 1

    print(f"Created {total} synthetic ITP files in '{out_dir}'")
    print(f"  -> {n_per_class} lipids, {n_per_class} polymers, {n_per_class} small molecules")
    print(f"\nNext step:  python train.py")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--n_mols", type=int, default=20,
                   help="Number of molecules per class (lipid/polymer/small)")
    p.add_argument("--out",    default="data/raw/martini3")
    args = p.parse_args()
    main(args.n_mols, args.out)
